version: '3'

services:
  db:
     image: postgres:9.6
     env_file: .env
     networks:
       - api-network

  redis:
    image: redis:3.2.11-alpine
    networks:
      - api-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./www:/var/www
    depends_on:
      - redis
      - db
    ports:
      - 8080:80
    networks:
      - api-network
    entrypoint: /var/start.sh

networks:
  api-network: {}